import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import HeroLayout from "@/components/Layouts/HeroLayout";
import IntroContent from "@/components/Layouts/IntroContent";
import { useEffect, useState } from "react";
import Skills from "@/components/Layouts/Skills";
import Personal from "@/components/Subsections/Landing/Personal";
import Experience from "@/components/Subsections/Landing/Experience";
import Interest from "@/components/Subsections/Landing/Interest";
import Testimonials from "@/components/Subsections/Landing/Testimonials";
import Connect from "@/components/Subsections/Landing/Connect";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div>
        <HeroLayout />
        <IntroContent />
        <Skills />
        <Personal />
        <Experience />
        <Interest />
        <Testimonials />
        <Connect />
      </div>
      <Footer />
    </>
  );
}
